static_sites:
  - name: inventrack-frontend
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html


